### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Khey17** [hangyu94/Ada-CM#14]
==> Preparing RAF-DB
Traceback (most recent call last):
  File "c:\Users\Karth\Downloads\Ada_CM\main.py", line 406, in <module>
    main()
  File "c:\Users\Karth\Downloads\Ada_CM\main.py", line 109, in main
    train_labeled_set, train_unlabeled_set, test_set = dataset.get_raf(args.train_root, args.label_train, args.test_root, args.label_test, args.n_labeled, transform_train=transform_train, transform_val=transform_val)
  File "c:\Users\Karth\Downloads\Ada_CM\dataset\raf.py", line 26, in get_raf
    train_labeled_idxs, train_unlabeled_idxs = data_split(train_file_list, int(n_labeled))
  File "c:\Users\Karth\Downloads\Ada_CM\dataset\raf.py", line 49, in data_split
    labels = target_read(filename)
  File "c:\Users\Karth\Downloads\Ada_CM\dataset\raf.py", line 44, in target_read
    _, label_name = info.split(' ')
ValueError: too many values to unpack (expected 2)

**Comment by xlg20000904** [comment]
How do you do for this problem ?  I meet the same problem
